/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package javagame;

import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javagame.entities.Combatant;
import javagame.entities.Item;
import javax.swing.DefaultListModel;
import javax.swing.JLabel;
import javax.swing.text.BadLocationException;
import javax.swing.text.Document;
import javax.swing.text.Style;
import javax.swing.text.StyleConstants;
import javax.swing.text.StyledDocument;
import javax.swing.text.html.HTMLDocument;

/**
 *
 * @author julia
 */
public class GameWindow extends javax.swing.JFrame {

    JavaGame javaGame = new JavaGame(this);
    private Item selectedItem = null;
    private int selectedIndex = 0;
    DefaultListModel<String> model;
    private Style style;
    
    /**
     * Creates new form GameWindow
     */
    public GameWindow() {
        initComponents();
        hideAllButtons();
        panelEnemy.setVisible(false);
        buttonUseItem.setVisible(false);
        model = new DefaultListModel<>();
        inventoryList.setModel(model);
        style = gameConsole.addStyle("style", null);
        updateStats();
        consoleLog("3... 2... 1... Let the games begin!");
        consoleLog("Do you run into the pile of loot, or do you run away?");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        panelYou = new javax.swing.JPanel();
        labelName = new javax.swing.JLabel();
        labelHealth = new javax.swing.JLabel();
        labelStrength = new javax.swing.JLabel();
        labelSpeed = new javax.swing.JLabel();
        labelIntelligence = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        labelXP = new javax.swing.JLabel();
        labelHolding = new javax.swing.JLabel();
        labelLocation = new javax.swing.JLabel();
        panelEnemy = new javax.swing.JPanel();
        labelNameEnemy = new javax.swing.JLabel();
        labelHealthEnemy = new javax.swing.JLabel();
        labelStrengthEnemy = new javax.swing.JLabel();
        labelSpeedEnemy = new javax.swing.JLabel();
        labelIntelligenceEnemy = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        labelTurn = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        inventoryList = new javax.swing.JList<>();
        jLabel3 = new javax.swing.JLabel();
        buttonUseItem = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        gameConsole = new javax.swing.JTextPane();
        jPanel4 = new javax.swing.JPanel();
        buttonAdvance = new javax.swing.JButton();
        buttonAttack = new javax.swing.JButton();
        buttonBlock = new javax.swing.JButton();
        buttonContinue = new javax.swing.JButton();
        buttonAbandon = new javax.swing.JButton();
        buttonFlee = new javax.swing.JButton();
        buttonRest = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Monster Game");
        setBackground(new java.awt.Color(255, 102, 102));
        setForeground(new java.awt.Color(0, 204, 0));

        jPanel1.setBackground(new java.awt.Color(255, 255, 204));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        panelYou.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelName.setText("Name:");

        labelHealth.setText("Health: 100");

        labelStrength.setText("Strength: 10");

        labelSpeed.setText("Speed: 10");

        labelIntelligence.setText("Intelligence: 10");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("You");

        labelXP.setText("XP: 0");

        labelHolding.setText("Holding: Nothing");

        labelLocation.setText("Location: Spawn");

        javax.swing.GroupLayout panelYouLayout = new javax.swing.GroupLayout(panelYou);
        panelYou.setLayout(panelYouLayout);
        panelYouLayout.setHorizontalGroup(
            panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYouLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelYouLayout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addGroup(panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelName)
                            .addComponent(labelHealth)
                            .addComponent(labelStrength)
                            .addComponent(labelSpeed)
                            .addComponent(labelIntelligence)
                            .addComponent(labelXP)
                            .addComponent(labelHolding)
                            .addComponent(labelLocation, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        panelYouLayout.setVerticalGroup(
            panelYouLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelYouLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHealth)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStrength)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSpeed)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIntelligence)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelXP)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHolding)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelLocation)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        panelEnemy.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelNameEnemy.setText("Name: player");

        labelHealthEnemy.setText("Health: 100");

        labelStrengthEnemy.setText("Strength: 10");

        labelSpeedEnemy.setText("Speed: 10");

        labelIntelligenceEnemy.setText("Intelligence: 10");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Enemy");

        javax.swing.GroupLayout panelEnemyLayout = new javax.swing.GroupLayout(panelEnemy);
        panelEnemy.setLayout(panelEnemyLayout);
        panelEnemyLayout.setHorizontalGroup(
            panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnemyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(panelEnemyLayout.createSequentialGroup()
                        .addGroup(panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNameEnemy)
                            .addComponent(labelHealthEnemy)
                            .addComponent(labelStrengthEnemy)
                            .addComponent(labelSpeedEnemy)
                            .addComponent(labelIntelligenceEnemy))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        panelEnemyLayout.setVerticalGroup(
            panelEnemyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnemyLayout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelNameEnemy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelHealthEnemy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelStrengthEnemy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelSpeedEnemy)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelIntelligenceEnemy)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        labelTurn.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelTurn.setText("Turn: 0");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(labelTurn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(labelTurn, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        inventoryList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        inventoryList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inventoryListMouseClicked(evt);
            }
        });
        inventoryList.addListSelectionListener(new javax.swing.event.ListSelectionListener() {
            public void valueChanged(javax.swing.event.ListSelectionEvent evt) {
                inventoryListValueChanged(evt);
            }
        });
        jScrollPane2.setViewportView(inventoryList);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Inventory");

        buttonUseItem.setText("Use");
        buttonUseItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonUseItemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(buttonUseItem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(3, 3, 3)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonUseItem))
        );

        gameConsole.setEditable(false);
        gameConsole.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jScrollPane3.setViewportView(gameConsole);

        buttonAdvance.setText("Explore");
        buttonAdvance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAdvanceActionPerformed(evt);
            }
        });

        buttonAttack.setText("Attack");
        buttonAttack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAttackActionPerformed(evt);
            }
        });

        buttonBlock.setText("Block");
        buttonBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBlockActionPerformed(evt);
            }
        });

        buttonContinue.setText("Loot");
        buttonContinue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonContinueActionPerformed(evt);
            }
        });

        buttonAbandon.setText("Abandon");
        buttonAbandon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAbandonActionPerformed(evt);
            }
        });

        buttonFlee.setText("Flee");
        buttonFlee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFleeActionPerformed(evt);
            }
        });

        buttonRest.setText("Rest");
        buttonRest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRestActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonAbandon, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonFlee, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonRest, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(251, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonAdvance, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAttack, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonBlock, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonContinue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAbandon, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonFlee, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonRest, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 1058, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelYou, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelEnemy, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(panelYou, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(panelEnemy, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAdvanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAdvanceActionPerformed
        javaGame.advanceTurn();
        
    }//GEN-LAST:event_buttonAdvanceActionPerformed

    private void buttonAttackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAttackActionPerformed
        javaGame.doBattleOption(EnumBattleOption.ATTACK);
        javaGame.incrementTurn(1);
    }//GEN-LAST:event_buttonAttackActionPerformed

    private void buttonBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBlockActionPerformed
        javaGame.doBattleOption(EnumBattleOption.BLOCK);
        javaGame.incrementTurn(1);
    }//GEN-LAST:event_buttonBlockActionPerformed

    private void buttonContinueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonContinueActionPerformed
        javaGame.lootPileContinue();
        javaGame.incrementTurn();
    }//GEN-LAST:event_buttonContinueActionPerformed

    private void buttonAbandonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAbandonActionPerformed
        javaGame.lootPileAbandon();
        javaGame.incrementTurn();
    }//GEN-LAST:event_buttonAbandonActionPerformed

    private void inventoryListValueChanged(javax.swing.event.ListSelectionEvent evt) {//GEN-FIRST:event_inventoryListValueChanged
        
    }//GEN-LAST:event_inventoryListValueChanged

    private void inventoryListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inventoryListMouseClicked
        try {
            selectedItem = javaGame.getPlayerInventory().get(inventoryList.getSelectedIndex());
            buttonUseItem.setVisible(true);
            buttonUseItem.setText(selectedItem.getUseButtonText());
        } catch (ArrayIndexOutOfBoundsException e) {
            selectedItem = null;
            buttonUseItem.setVisible(false);
        }
    }//GEN-LAST:event_inventoryListMouseClicked

    private void buttonUseItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonUseItemActionPerformed
        if (selectedItem != null) {
            selectedItem.useItem(javaGame);
        }
    }//GEN-LAST:event_buttonUseItemActionPerformed

    private void buttonFleeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFleeActionPerformed
        javaGame.doBattleOption(EnumBattleOption.FLEE);
    }//GEN-LAST:event_buttonFleeActionPerformed

    private void buttonRestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRestActionPerformed
        javaGame.rest();
    }//GEN-LAST:event_buttonRestActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GameWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GameWindow().setVisible(true);
                
            }
        });
    }

    public void consoleLog(String message) {
        StyledDocument doc = gameConsole.getStyledDocument();
        StyleConstants.setForeground(style, Color.BLACK);
        try {
            doc.insertString(doc.getLength(), message+"\n", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    public void consoleLogColor(String message, Color color) {
        StyledDocument doc = gameConsole.getStyledDocument();
        StyleConstants.setForeground(style, color);
        try {
            doc.insertString(doc.getLength(), message+"\n", style);
        } catch (BadLocationException ex) {
            Logger.getLogger(GameWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
    }    

    public void clearConsole() {
        gameConsole.setText("");
    }
    
    public void updateInventory() {
        selectedIndex = inventoryList.getSelectedIndex();
        model.clear();
        for (Item item : javaGame.getPlayerInventory()) {
            model.addElement(item.getName());
        }
        inventoryList.setSelectedIndex(selectedIndex);
    }
    
    public int getSelectedIndex() {
        return selectedIndex;
    }
    
    public Item getSelectedItem() {
        return selectedItem;
    }
    
    public void resetSelectedIndex() {
        selectedIndex = -1;
        inventoryList.clearSelection();
    }
    
    public void updateStats() {
        // update player panel
        Combatant playerCombatant = javaGame.getPlayer();
        labelName.setText("Name: "+playerCombatant.getName());
        labelHealth.setText("Health: "+playerCombatant.getHealth());
        labelStrength.setText("Strength: "+playerCombatant.getStrength());
        labelSpeed.setText("Speed: "+playerCombatant.getSpeed());
        labelIntelligence.setText("Intelligence: "+playerCombatant.getIntelligence());
        labelTurn.setText("Time: "+javaGame.getTimeString());
        labelHolding.setText("Weapon: " + playerCombatant.getWeapon().getName()+
                " (damage: "+playerCombatant.getDamage()+")");
        labelXP.setText("XP: "+javaGame.getXP());
        labelLocation.setText("Location: " +javaGame.getLocation().name);
        // update enemy panel
        if (javaGame.getGameState() == EnumGameState.FIGHTING) {
            panelEnemy.setVisible(true);
            Combatant enemyCombatant = javaGame.getCurrentBattle().getEnemyCombatant();
            labelNameEnemy.setText("Name: "+enemyCombatant.getName());
            labelHealthEnemy.setText("Health: "+enemyCombatant.getHealth());
            labelStrengthEnemy.setText("Strength: "+enemyCombatant.getStrength());
            labelSpeedEnemy.setText("Speed: "+enemyCombatant.getSpeed());
            labelIntelligenceEnemy.setText("Intelligence: "+enemyCombatant.getIntelligence());
        } else {
            panelEnemy.setVisible(false);
        }
        // update action buttons
        hideAllButtons();
        if (null != javaGame.getGameState()) switch (javaGame.getGameState()) {
            case EXPLORING:
                buttonAdvance.setVisible(true);
                buttonRest.setVisible(true);
                break;
            case FIGHTING:
                buttonAttack.setVisible(true);
                buttonBlock.setVisible(true);
                buttonFlee.setVisible(true);
                break;
            case LOOTING:
                buttonContinue.setVisible(true);
                buttonAbandon.setVisible(true);
                break;
            default:
                break;
        }
        updateInventory();
    }
    
    public void hideAllButtons() {
        buttonAdvance.setVisible(false);
        buttonAttack.setVisible(false);
        buttonBlock.setVisible(false);
        buttonContinue.setVisible(false);
        buttonAbandon.setVisible(false);
        buttonFlee.setVisible(false);
        buttonRest.setVisible(false);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAbandon;
    private javax.swing.JButton buttonAdvance;
    private javax.swing.JButton buttonAttack;
    private javax.swing.JButton buttonBlock;
    private javax.swing.JButton buttonContinue;
    private javax.swing.JButton buttonFlee;
    private javax.swing.JButton buttonRest;
    private javax.swing.JButton buttonUseItem;
    private javax.swing.JTextPane gameConsole;
    private javax.swing.JList<String> inventoryList;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel labelHealth;
    private javax.swing.JLabel labelHealthEnemy;
    private javax.swing.JLabel labelHolding;
    private javax.swing.JLabel labelIntelligence;
    private javax.swing.JLabel labelIntelligenceEnemy;
    private javax.swing.JLabel labelLocation;
    private javax.swing.JLabel labelName;
    private javax.swing.JLabel labelNameEnemy;
    private javax.swing.JLabel labelSpeed;
    private javax.swing.JLabel labelSpeedEnemy;
    private javax.swing.JLabel labelStrength;
    private javax.swing.JLabel labelStrengthEnemy;
    private javax.swing.JLabel labelTurn;
    private javax.swing.JLabel labelXP;
    private javax.swing.JPanel panelEnemy;
    private javax.swing.JPanel panelYou;
    // End of variables declaration//GEN-END:variables
}
